### ISSUE TITLE
Error with bindings file

### ISSUE THREAD

**Issue by ghost** [wankdanker/node-odbc#73]
Hi there !

I've this issue sometimes when I make changes to package.json:

```
Error: Could not locate the bindings file. Tried:
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/build/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/build/Debug/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/build/Release/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/out/Debug/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/Debug/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/out/Release/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/Release/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/build/default/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/compiled/10.15.3/darwin/x64/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/addon-build/release/install-root/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/addon-build/debug/install-root/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/addon-build/default/install-root/odbc_bindings.node
[1]  → /Users/qlecler/courtier_ph/node_modules/odbc/lib/binding/node-v64-darwin-x64/odbc_bindings.node
[1]     at bindings (/Users/qlecler/courtier_ph/node_modules/bindings/bindings.js:126:9)
[1]     at Object.<anonymous> (/Users/qlecler/courtier_ph/node_modules/odbc/lib/odbc.js:18:31)
[1]     at Module._compile (internal/modules/cjs/loader.js:701:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
[1]     at Module.load (internal/modules/cjs/loader.js:600:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[1]     at Module.require (internal/modules/cjs/loader.js:637:17)
[1]     at require (internal/modules/cjs/helpers.js:22:18)
[1]     at Object.<anonymous> (/Users/qlecler/courtier_ph/server/utils/db.js:1:76)
[1] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by wankdanker** [comment]
Sorry it's been so long. If you are still having this problem, please re-open this issue and let me know what odbc package version you are using.
